server:
  port: 8081

spring:
  application:
    name: auth-service
  security:
    user:
      name: ${EUREKA_USER:admin}
      password: ${EUREKA_PASS:secret}

jwt:
  secret: ${JWT_SECRET:}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true    
    service-url:
      defaultZone: ${EUREKA_URL:http://${EUREKA_USER:admin}:${EUREKA_PASS:secret}@localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO

